name: Dispatch Update Submodule
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update to Git Blog Project
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: camillegiuliano/ParentTest
          event-type: update-submodule